--AQUI PONEMOS LAS PLANILLAS QUE NO APARECEN EN EL REPORTE
SELECT
	EMPRESA,
	PLANILLA, 
	NUEVA_PLANILLA,
* FROM
	anexos_riesgos2..Anx06_preliminar 
WHERE
	FechaCorte1 = '20231130'
AND
	PLANILLA like '%D DE SALUD TACN%'

--AQUÍ LAS BUSCAMOS EN LA TABLA DE PLANILLAS
DECLARE @EMPRESANILLA VARCHAR(50) = '%D DE SALUD TACN%'
SELECT * FROM  Anexos_Riesgos..planilla2
WHERE NUEVA_PLANILLA LIKE @EMPRESANILLA
OR NUEVA_PLANILLA_creada LIKE @EMPRESANILLA
OR Empresa LIKE @EMPRESANILLA
OR planilla_corregida LIKE @EMPRESANILLA

-- update anexos_riesgos2..anx06_preliminar
-- set NUEVA_PLANILLA = 'DIRECCION REGIONAL DE SALUD TUMBES - NOMBRADOS'
-- where NUEVA_PLANILLA = 'DIRECCION REGIONAL DE SALUD TUMBES - ACTIVOS'

----------------------------------------------
--AQUÍ LAS AÑADIMOS PARA QUE APAREZCAN
-- LA COLUMNA NUEVA_PLANILLA_creada debe tener el nombre correcto
-- LA COLUMNA NUEVA_PLANILLA tiene el nombre que queremos corregir
INSERT INTO Anexos_Riesgos..planilla2
VALUES (
'RED DE SALUD TACNA - NOMBRADOS',
'RED DE SALUD TACNA - NOMBRADOS',
'RED DE SALUD TACNA',
'RED DE SALUD TACNA - NOMBRADOS'
        )
