--AQUI PONEMOS LAS PLANILLAS QUE NO APARECEN EN EL REPORTE
select 
	EMPRESA,
	PLANILLA, 
	NUEVA_PLANILLA,
* from 
	anexos_riesgos2..Anx06_preliminar 
where
	FechaCorte1 = '20230831'
and 
	PLANILLA like '%stratt%'



--AQUÍ LAS BUSCAMOS EN EL RPEORTE
DECLARE @EMPRESANILLA VARCHAR(50) = '%ed%tac%'
SELECT * FROM  Anexos_Riesgos..planilla2
WHERE NUEVA_PLANILLA LIKE @EMPRESANILLA
OR NUEVA_PLANILLA_creada LIKE @EMPRESANILLA
OR Empresa LIKE @EMPRESANILLA
OR planilla_corregida LIKE @EMPRESANILLA

update anexos_riesgos2..anx06_preliminar
set NUEVA_PLANILLA = 'DIRECCION REGIONAL DE SALUD TUMBES - NOMBRADOS'
where NUEVA_PLANILLA = 'DIRECCION REGIONAL DE SALUD TUMBES - ACTIVOS'

----------------------------------------------
--AQUÍ LAS AÑADIMOS PARA QUE APAREZCAN
INSERT INTO Anexos_Riesgos..planilla2
VALUES (
'DIRECCION REGIONAL DE EDUCACION TACNA - CONTRATADOS',
'DIRECCION REGIONAL DE EDUCACION TACNA - CONTRATADOS',
'DIRECCION REGIONAL DE EDUCACION TACNA',
'DIRECCION REGIONAL DE EDUCACION TACNA - CONTRATADOS'
)


