DECLARE @planilla_TXT  as varchar(255) = '%mun%prov%arequ%'
DECLARE @FECHA_CORTE AS DATETIME = '20240229'
--AQUI PONEMOS LAS PLANILLAS QUE NO APARECEN EN EL REPORTE

SELECT
	UPPER(A.EMPRESA) as 'EMPRESA',
	A.PLANILLA, 
	A.NUEVA_PLANILLA,
    CASE
		WHEN A.PLANILLA = 'PLANILLA LIQUIDADOS' THEN A.NUEVA_PLANILLA
		ELSE A.PLANILLA
		END AS 'PLANILLA BIEN',
	a.Departamento, a.[Dpto Negocio],
	Situacion_Credito, Origen_Coopac, 
	P.EMPRESA, 
    P.PLANILLA_CORREGIDA as 'PLANILLA_CORREGIDA',
	a.Departamento
FROM  
	anexos_riesgos2..Anx06_preliminar A

LEFT JOIN Anexos_Riesgos..PLANILLA2 P
	ON (LTRIM(RTRIM(A.NUEVA_PLANILLA)) =  LTRIM(RTRIM(P.NUEVA_PLANILLA)))
	WHERE FechaCorte1 = @FECHA_CORTE
AND
	PLANILLA like @planilla_TXT

--AQUÍ LAS BUSCAMOS EN LA TABLA DE PLANILLAS
DECLARE @EMPRESANILLA VARCHAR(50) = @planilla_TXT
SELECT * FROM  Anexos_Riesgos..planilla2
WHERE NUEVA_PLANILLA LIKE @EMPRESANILLA
OR NUEVA_PLANILLA_creada LIKE @EMPRESANILLA
OR Empresa LIKE @EMPRESANILLA
OR planilla_corregida LIKE @EMPRESANILLA

-- update anexos_riesgos2..anx06_preliminar
-- set NUEVA_PLANILLA = 'DIRECCION REGIONAL DE SALUD TUMBES - NOMBRADOS'
-- where NUEVA_PLANILLA = 'DIRECCION REGIONAL DE SALUD TUMBES - ACTIVOS'

----------------------------------------------
--AQUÍ LAS AÑADIMOS PARA QUE APAREZCAN
-- LA COLUMNA NUEVA_PLANILLA_creada debe tener el nombre correcto
-- LA COLUMNA NUEVA_PLANILLA tiene el nombre que queremos corregir

/*

INSERT INTO Anexos_Riesgos..planilla2
VALUES (
'MUNICIPALIDAD DISTRITAL DE CASA GRANDE - NOMBRADOS',
'MUNICIPALIDAD DISTRITAL DE CASA GRANDE - NOMBRADOS',
'MUNICIPALIDAD DISTRITAL DE CASA GRANDE',
'MUNICIPALIDAD DISTRITAL DE CASA GRANDE - NOMBRADOS'
        )




		update Anexos_Riesgos..planilla2
		set NUEVA_PLANILLA_creada = 'UNIVERSIDAD NACIONAL DE TUMBES - ACTIVOS'
		WHERE NUEVA_PLANILLA = 'UNIVERSIDAD NACIONAL DE TUMBES - ACTIVOS'


		UPDATE anexos_riesgos3..ANX06
		SET EMPRESA = 'EMPRESA MUNICIPAL DE AGUA POTABLE Y ALCANTARILLADO DE PISCO S.A.'
		WHERE EMPRESA LIKE '%EMPRESA MUNICIPAL DE AGUA POTABLE Y ALCANTARILLADO DE PISCO S.A.%'

		*/
		-- select * from anexos_riesgos2..anx06_preliminar
		-- select * from Comercial..Anx06
		-- select * from anexos_riesgos3..ANX06
		-- select * from COSECHA..cosecha_nuevo



